name: round2newsapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  webview_flutter: ^3.0.1
  shared_preferences: ^2.2.3
  google_generative_ai: ^0.3.1



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Jacquard
       fonts:
         - asset: fonts/Jacquard24-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Newsreader
       fonts:
         - asset: fonts/Newsreader-Italic-VariableFont_opsz,wght.ttf
           style: italic
         - asset: fonts/Newsreader-VariableFont_opsz,wght.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
